services:
  - type: web
    name: commune-flask-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python render_start.py
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT --timeout 120 --keep-alive 2 run:app
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: commune-db
          property: connectionString

databases:
  - name: commune-db
    plan: free
